version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: on-failure
    container_name: postgresDB
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=companies
    ports:
      - '3307:3306'
    volumes:
      - data-postgress-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
  mongo:
    image: bitnami/mongodb
    container_name: mongoDB
    env_file: ./.env
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: report_details
    ports:
      - '27018:27017'
    volumes:
      - data-mongo-db:/data/db

volumes:
  data-postgress-db:
  data-mongo-db: